### ISSUE TITLE
what is the problem?

### ISSUE THREAD

**Issue by turalyf** [senges/lightshot#6]
![image](https://user-images.githubusercontent.com/70627343/93734929-e23cba00-fbe3-11ea-86d9-e5c0a7667469.png)

![image](https://user-images.githubusercontent.com/70627343/93734938-e7016e00-fbe3-11ea-878a-985dc330652a.png)

**Comment by senges** [comment]
`pull.sh` needs to be executable

```
chmod +x pull.sh
```

**Comment by turalyf** [comment]
Big thank 💪🏻
